sudo: required

compiler:
  - gcc
  - clang

language: cpp

arch:
  packages:
    - cmake
    - sfml
  script:
    - make

matrix:
  include:
    - os: osx
      language: cpp
      compiler:
        - gcc
        - clang
      before_script:
        - brew install sfml
      script:
        - make

script:
- "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"
