sudo: required

language: cpp

compiler:
  - gcc
  - clang

archarch:
  packages:
    - cmake
    - sfml
  script:
    - make

script:
  - "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"
