sudo: required

compiler:
  - gcc
  - clang

language: cpp

archlinux:
  packages:
    - cmake
    - sfml
  script:
    - make

matrix:
  include:
    - os: osx
      compiler: gcc
      before_script:
        - HOMEBREW_NO_AUTO_UPDATE=1 brew install sfml
      script:
        - make
    - os: osx
      compiler: clang
      before_script:
        - HOMEBREW_NO_AUTO_UPDATE=1 brew install sfml
      script:
        - make

script:
- "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"

addons:
  artifacts:
    paths:
      - ./*
