os: linux

compiler:
  - gcc
  - clang

language: cpp

archlinux:
  packages:
    - cmake
    - xorg
    - openal
    - libvorbis
    - flac
  script:
    - mkdir lib/build-SFML
    - cmake
        -Blib/build-SFML
        -DBUILD_SHARED_LIBS=OFF
        lib/SFML
    - make -C lib/build-SFML
    - make
        SFML_STATIC=y
        EXTRA_LDFLAGS="-L./lib/build-SFML/lib'
        EXTRA_CXXFLAGS="-isystem ./lib/SFML/include"

jobs:
  include:
    - os: osx
      compiler: gcc
      script:
        - mkdir lib/build-SFML
        - pushd lib/build-SFML
            && cmake -DBUILD_SHARED_LIBS=OFF ../SFML
            && popd
        - make -C lib/build-SFML
        - make \
            SFML_STATIC=y \
            EXTRA_LDFLAGS="-L./lib/build-SFML/lib" \
            EXTRA_CXXFLAGS="-isystem ./lib/SFML/include" \
            Q=
    - os: osx
      compiler: clang
      script:
        - mkdir lib/build-SFML
        - pushd lib/build-SFML
            && cmake -DBUILD_SHARED_LIBS=OFF ../SFML
            && popd
        - make -C lib/build-SFML
        - make
            SFML_STATIC=y
            EXTRA_LDFLAGS=-L./lib/build-SFML/lib
            EXTRA_CXXFLAGS="-isystem
            ./lib/SFML/include"

script:
- "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"
