
language: c++
os: osx

before_script:
    - brew install sfml

script: 
    - make clean cover
    - LD_PRELOAD=$(pwd)/lib/build/libBox2D.so ./demo
    - gcov build/main.cpp

compiler: 
    - gcc
      
after_success:
    - bash <(curl -s https://codecov.io/bash)
