sudo: required

language: cpp

compiler:
  - gcc
  - clang

arch:
  packages:
    - cmake
    - sfml
  script:
    - make

matrix:
  include:
    - os: linux
      script:
      - "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"
    - os: osx
      before_script:
        - brew install sfml
      script:
        - make
