sudo: required

compiler:
  - gcc
  - clang

language: cpp

archlinux:
  packages:
    - cmake
    - xorg
    - openal
  script:
    - mkdir lib/build-SFML
    - cmake -Blib/build-SFML -DBUILD_SHARED_LIBS=OFF lib/SFML
    - make -C lib/build-SFML
    - make SFML_STATIC=y EXTRA_LDFLAGS=-L./lib/build-SFML/lib EXTRA_CXXFLAGS="-isystem ./lib/SFML/include"

matrix:
  include:
    - os: osx
      compiler: gcc
      script:
        - mkdir lib/build-SFML
        - cmake -Blib/build-SFML -DBUILD_SHARED_LIBS=OFF lib/SFML
        - make -C lib/build-SFML
        - make SFML_STATIC=y EXTRA_LDFLAGS=-L./lib/build-SFML/lib EXTRA_CXXFLAGS="-isystem ./lib/SFML/include"
    - os: osx
      compiler: clang
      script:
        - mkdir lib/build-SFML
        - cmake -Blib/build-SFML -DBUILD_SHARED_LIBS=OFF lib/SFML
        - make -C lib/build-SFML
        - make SFML_STATIC=y EXTRA_LDFLAGS=-L./lib/build-SFML/lib EXTRA_CXXFLAGS="-isystem ./lib/SFML/include"

script:
- "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"
