
language: c++
os: osx

before_script:
    - brew cask install box2d

script: 
    - make clean cover
    - ./demo
    - gcov build/main.cpp

compiler: 
    - gcc
      
after_success:
    - bash <(curl -s https://codecov.io/bash)
